-- generated using ./src/import_keybind_names.luau
-- do not manually edit this

export type keybind_name =
| string
| "toggle_radio" -- Use Radio
| "flash_toggle" -- Toggle Flashlight
| "interaction" -- Interact
| "point_aim" -- Point Aim
| "space" -- Jump
| "inspect" -- Inspect
| "leaderboard" -- Toggle Leaderboard
| "editor_move_gun" -- Move weapon in editor
| "lean_left" -- Lean Left
| "chat_toggle" -- Toggle chat
| "aim" -- Aim, Underhand throw grenade
| "equip_primary" -- Switch to primary
| "chat_focus" -- Type in chat
| "move_backward" -- Move backward
| "move_down" -- Move down in the editor
| "firemode" -- Switch Firemode
| "night_vision" -- Toggle NV
| "run" -- Run
| "editor_aim" -- Aim in editor
| "prone" -- Prone
| "lean_right" -- Lean Right
| "switch_scope" -- Switch Scope
| "switch_reticle" -- Switch Reticle
| "gangsta_control" -- Gangsta control [has to be enabled by an admin]
| "shove" -- Shove Weapon
| "toggle_insitux" -- Toggle Insitux
| "reload" -- Reload, Magcheck
| "prompt_confirm" -- Prompt: Select highlighted option
| "equip_throwable2" -- Switch to utility 2
| "move_up" -- Move up in the editor
| "fire" -- Fire, Throw grenade
| "alt_key" -- [READONLY] Alt key
| "move_left" -- Move left
| "move_forward" -- Move forward
| "death_view_respawn" -- Death view: Respawn
| "hide_tutorial" -- Hide ingame tutorial
| "death_view_leave" -- Death view: Leave
| "laser_toggle" -- Toggle Laser
| "equip_secondary" -- Switch to secondary
| "move_right" -- Move right
| "hide_editor_ui" -- Toggle Editor UI
| "equip_throwable1" -- Switch to utility 1
| "crouch" -- Crouch
| "chat_focus_team" -- Type in teamchat
